version: '3.8'

services:
  api:
    build: .
    container_name: api
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/dates_facts_db
      - PORT=${PORT}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dates_facts_db

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data: