"""inital_migration

Revision ID: ca99027ca116
Revises: 
Create Date: 2022-04-11 20:49:28.624763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca99027ca116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=50), nullable=False),
    sa.Column('fact', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'month', name='uix_day_month')
    )
    op.create_index(op.f('ix_date_facts_id'), 'date_facts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_date_facts_id'), table_name='date_facts')
    op.drop_table('date_facts')
    # ### end Alembic commands ###
